// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace iCalc {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("CalcView")]
	public partial class CalcView {
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("buttonPressed:")]
		partial void buttonPressed (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				return ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
			}
			set {
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("button")]
		private MonoTouch.UIKit.UIButton button {
			get {
				return ((MonoTouch.UIKit.UIButton)(this.GetNativeField("button")));
			}
			set {
				this.SetNativeField("button", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("resultLabel")]
		private MonoTouch.UIKit.UILabel resultLabel {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("resultLabel")));
			}
			set {
				this.SetNativeField("resultLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("textBox1")]
		private MonoTouch.UIKit.UITextField textBox1 {
			get {
				return ((MonoTouch.UIKit.UITextField)(this.GetNativeField("textBox1")));
			}
			set {
				this.SetNativeField("textBox1", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("textBox2")]
		private MonoTouch.UIKit.UITextField textBox2 {
			get {
				return ((MonoTouch.UIKit.UITextField)(this.GetNativeField("textBox2")));
			}
			set {
				this.SetNativeField("textBox2", value);
			}
		}
	}
}
